### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by atgreen** [boogsbunny/stripe#1]
https://github.com/ocicl/stripe/actions/runs/11092034481/job/30816555113#step:2:42775

**Comment by boogsbunny** [comment]
Will look into this, thanks!

**Comment by boogsbunny** [comment]
[This commit](https://github.com/boogsbunny/stripe/commit/2d56a37b01c7d9c77facbb17f47502e9f7287aed) should fix this.

**Comment by boogsbunny** [comment]
Looks like it [passed](https://github.com/ocicl/stripe/actions/runs/11116793397), thanks for flagging!
