### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by atgreen** [boogsbunny/stripe#2]
...from today's changes:
https://github.com/ocicl/stripe/actions/runs/11763654167/job/32767905849

This is the change: d6ed3fdc81627631fedfe53c502807f3da8013c7

**Comment by boogsbunny** [comment]
Thanks, fixed here [a314dd9](https://github.com/boogsbunny/stripe/commit/a314dd97f7ce36427c504975f0802d52ae3fe822).
